#!/bin/sh
# Usage: sockstat [-l4 | -l6]
#   -l4  Show only IPv4 connections
#   -l6  Show only IPv6 connections

if [ "$1" = "-l4" ]; then
    filter="IPv4"
elif [ "$1" = "-l6" ]; then
    filter="IPv6"
else
    filter=""
fi

# Print the header
printf "%-10s %-10s %-6s %-4s %-6s %s\n" "USER" "COMMAND" "PID" "FD" "PROTO" "LOCAL ADDRESS"

# Run lsof and filter output with awk
doas lsof -nP -iTCP -sTCP:LISTEN -iUDP | awk -v f="$filter" '{
    if ($1 == "COMMAND") next;
    if (f != "" && $5 != f) next;
    printf "%-10s %-10s %-6s %-4s %-6s %s\n", $3, $1, $2, $4, $8, $9;
}'
